FROM golang:1.23 AS builder

ENV GIN_MODE=release
ENV CGO_ENABLED=0
ENV GOOS=linux

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o ocserv_api .

FROM alpine:latest

RUN mkdir -p /app

WORKDIR /app

COPY --from=builder /app/ocserv_api .

COPY ./scripts/server.sh /server.sh

RUN chmod +x /app/ocserv_api /server.sh

CMD ["/server.sh"]