FROM alpine:latest

ENV GIN_MODE=release
ENV CGO_ENABLED=0
ENV GOOS=linux

RUN mkdir -p /app

WORKDIR /app

COPY  ./ocserv_api .

COPY ./scripts/server.sh /server.sh

RUN chmod +x /app/ocserv_api /server.sh

CMD ["/server.sh"]