definitions:
  models.Site:
    properties:
      captcha_secret_key:
        type: string
      captcha_site_key:
        type: string
      default_traffic:
        type: number
      id:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/site:
    get:
      description: Get site configuration
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Site'
        "400":
          description: 'error": "Error message'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get site configuration
      tags:
      - site
swagger: "2.0"
